// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjY82OWBPPAQbdaD92Dr_C3Z34M4bY11w',
    appId: '1:411717930918:web:ebf7c7a48ac6bf8ea14967',
    messagingSenderId: '411717930918',
    projectId: 'shopelyzk',
    authDomain: 'shopelyzk.firebaseapp.com',
    databaseURL: 'https://shopelyzk-default-rtdb.firebaseio.com',
    storageBucket: 'shopelyzk.appspot.com',
    measurementId: 'G-T4CCF2K0RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8yfwcpzzygQurL6l62pRa4KQtUnRbl5g',
    appId: '1:411717930918:android:0911400b22cbef81a14967',
    messagingSenderId: '411717930918',
    projectId: 'shopelyzk',
    databaseURL: 'https://shopelyzk-default-rtdb.firebaseio.com',
    storageBucket: 'shopelyzk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb692EW1yALikmByKtkyMfIFD2rh0Hceo',
    appId: '1:411717930918:ios:7a1b9c47c0279acba14967',
    messagingSenderId: '411717930918',
    projectId: 'shopelyzk',
    databaseURL: 'https://shopelyzk-default-rtdb.firebaseio.com',
    storageBucket: 'shopelyzk.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb692EW1yALikmByKtkyMfIFD2rh0Hceo',
    appId: '1:411717930918:ios:7a1b9c47c0279acba14967',
    messagingSenderId: '411717930918',
    projectId: 'shopelyzk',
    databaseURL: 'https://shopelyzk-default-rtdb.firebaseio.com',
    storageBucket: 'shopelyzk.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjY82OWBPPAQbdaD92Dr_C3Z34M4bY11w',
    appId: '1:411717930918:web:e4d88423f45e7d22a14967',
    messagingSenderId: '411717930918',
    projectId: 'shopelyzk',
    authDomain: 'shopelyzk.firebaseapp.com',
    databaseURL: 'https://shopelyzk-default-rtdb.firebaseio.com',
    storageBucket: 'shopelyzk.appspot.com',
    measurementId: 'G-XS4GFHYNR2',
  );
}
